import Head from "next/head";
import Image from "next/image";
import Footer from "../sections/Footer";
import Header from "../sections/Header";
import Hero from "../sections/Hero";
import Main from "../sections/Main";
import Statistics from "../sections/statistics";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div style={{ height: "100%" }}>
      <Head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/assets/favicon/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/assets/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/assets/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <title>Get METADATA</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Hero />
      <Main />
      <Statistics />
      <Footer />
    </div>
  );
}
